name: Development Branch
on:
  push:
    branches-ignore:
      #- 'master'
      - 'homologation'
      - 'release*'

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Maven Package
        run: mvn -B clean package -DskipTests
      - name: Maven Verify
        run: mvn -B clean verify